auth:
  service:
    path: "http://auth-service.project-x:8081/"

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/project_x
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS}
