apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: dev.local/user-service:0.0.1
          imagePullPolicy: Never
          name: frontend
          ports:
            - containerPort: 4200